### ISSUE TITLE
Ott navigator playlist error

### ISSUE THREAD

**Issue by Nexus-Gits** [byte-capsule/Toffee-Channels-Link-Headers#1]
in ott navigator this ( https://raw.githubusercontent.com/Jeshan-akand/Toffee-Channels-Link-Headers/main/toffee_channel_data.json ) url add show problem like no channel available. check username password.

Please let me know how to fix the error @byte-capsule

**Comment by byte-capsule** [comment]
The problem has been fixed. Now it works perfectly.

Thank you 😊

**Comment by Nexus-Gits** [comment]
Thank you, for your reply and now it shows playback error and channels not play. Im from india if this is the reason for the channels not play and it shows playback error. Please help me @byte-capsule

**Comment by byte-capsule** [comment]
It works only on Bangladeshi IP. You can try with VPN

**Comment by Nexus-Gits** [comment]
> It works only on Bangladeshi IP. You can try with VPN

Other than vpn if any other way i use it from indian ip.

**Comment by byte-capsule** [comment]
There is no option to play from an Indian IP...
😔
